### ISSUE TITLE
List of Functions

### ISSUE THREAD

**Issue by fdahlberg** [sklose/NCalc2#10]
Hi,

I've been testing NCalc and I'm very impressed by the capabilities. 

Is it possible to get a list of the available functions in NCalc? I'm trying to write an editor where a user would input an expression that is evaluated by NCalc. I would like to highlight all the function names that are accepted by NCalc but am not sure how to get that list.

Kind Regards
Fredrik Dahlberg

**Comment by sklose** [comment]
It only ships with two functions out of the box: `if(cond, true, false)` and `in(search, element1, element2, ...)`. For any other functions you would have to register them explicitly with NCalc.

**Comment by fdahlberg** [comment]
Is that correct? I can see that for example Min, Max, Sin and Cos are working out of the box.

**Comment by sklose** [comment]
You are right, there are a few more functions built in for interpreted mode. You can find the list here: https://github.com/sklose/NCalc2/blob/a91bd827c8ce3e4fea1c942789073d9aa57d1cdf/src/NCalc/Domain/EvaluationVisitor.cs#L286. Those functions are not available when compiled to a lambda expression though.
