### ISSUE TITLE
Added support for overloading and the params keyword.

### ISSUE THREAD

**Issue by fadulalla** [sklose/NCalc2#20]
**Enhancement**
Hey!

I needed support for overloading and the params keyword so I went ahead and added them in a fork.
I opened a PR in case others have similar needs, here: #19 .. 

I am not sure if I was meant to open an issue before creating a PR, so here's an issue, just in case.

**Comment by sklose** [comment]
Hi fadulalla,

thanks for your contribution, that's a very neat feature to have. I just merged your PR. A new version with the feature should be published shortly by the build system.

-Sebastian
