### ISSUE TITLE
Fix overloading when parameters are non-primitive.

### ISSUE THREAD

**Issue by fadulalla** [sklose/NCalc2#29]
Hello, it's me again! :)

After using #20 for 6 months, I've come to realise that when searching for a method, if its parameters are of type object, it's treated as equal to any other overload with object parameters. Even if the objects' internal types are different. This caused mismatching types exceptions.

This stems from using `ToTypeCode()` instead of just the type when searching for a method. 
(I don't actually know if there's a need to use `TypeCode` when comparing parameters for methods.

I've made a PR ( #30 ) that addresses this issue, would appreciate if you could take a look and tell me what you think. Cheers.

Faris.

**Comment by sklose** [comment]
fadulalla, thanks for fixing this issue ... I merged the PR
