### ISSUE TITLE
Add support of unicode characters in parameters

### ISSUE THREAD

**Issue by nickger** [sklose/NCalc2#59]
Currently the string "Kälteleistung / 2" cannot be compiled, please, add support for unicode characters in parameters.

**Comment by Bykiev** [comment]
I've tried with the latest version and can't reproduce the issue with such code

```
var expr = new Expression("[Kälteleistung] / 2");
expr.Parameters["Kälteleistung"] = 10;
var res = expr.Evaluate();
```

I believe it's because you should use the square brackets with parameter name. Can be closed as not a bug

**Comment by nickger** [comment]
Should the brackets be inside or outside of the quotes?

**Comment by Bykiev** [comment]
I think there is no need for escaping parameter names with quotes, only the unicode strings. For ex:

https://github.com/sklose/NCalc2/blob/4e0338cbf84236087b793430aa91287270a1df05/test/NCalc.Tests/Fixtures.cs#L187-L190

**Comment by nickger** [comment]
Ok.
