### ISSUE TITLE
Restore original license information

### ISSUE THREAD

**Issue by sebastienros** [sklose/NCalc2#66]
I think the license from the original project got lost at some point

**Comment by sklose** [comment]
Could you point me to the original license? The old link to Codeplex doesn't work anymore and https://github.com/sheetsync/NCalc doesn't seem to have a license specified.

**Comment by sebastienros** [comment]
https://github.com/ncalc/ncalc/blob/master/LICENSE

It seems that the license was not available in the repos on codeplex, but exposed in the License tab.
