### ISSUE TITLE
ToLambda: ArgumentNullException if method not found in context

### ISSUE THREAD

**Issue by shatl** [sklose/NCalc2#7]
Update LambdaExpressionVistor to throw more specific exception if method was not found in context class.

Example:
`class ExpressionContext { } `
expression `Get([Param]) == 0' `.

'ToLambda<ExpressionContext,bool>()' throws `System.ArgumentNullException : Value cannot be null.
Parameter name: method`  - no method name (Get)  provided in exception

**Comment by sklose** [comment]
fixed in version 2.2.40 by @dgeller-OUHSC
